davmlaw/2024_assignment_5_adelaide_uni_bioinfo

- data/a1795973.txt
- docs/a1795973.txt
Hi, this pull request resolves the following issues previously raised. 
Issue #8 
- Removes 'XXXXXXX' from data/a1795973.txt, and 
Issue #9 
- Changes UPPERCASE words to lowercase in data/a1795973.txt
Please reach out if you need anything else :)
> Resolved 'XXXXXXX' and UPPERCASE bugs in data/a1795973.txt

- data/a1863615.txt
- docs/a1863615.txt
Hi,
this pull request fixes the following two issues:
#12:
**Issue**: 'XXXXXX' appeared in `data/a1863615.txt`.  
**Fix**: All occurrences of this bug have been removed from the file.
#13:
**Issue**: Some words in `data/a1863615.txt` were in all uppercase.  
**Fix**: The affected words have been changed back to lowercase.
Thanks for your work on maintaining this repository!
Oliver
> Fixes #12 and #13: Resolve 'XXXXXX' bug and correct uppercase words

- data/a1766804.txt
- docs/a1766804.txt
Hi there, 
This pull request resolves issues #10 and #11. 
The resolution of issue #10 removes all instances of 'XXXXXXX' present in data/a1766804.txt. 
The resolution of issue #11 changes all instances of words in UPPERCASE to be in lowercase in data/a1766804.txt. 
Please feel free to advise of any changes or further information is required!
> Resolved: UPPERCASE and XXXXXXX bugs in data/a1766804.txt

- data/a1839745.txt
- docs/a1839745.txt
Hi,
This pull request is to resolve issue #17 (removing the 'XXXXXXX' insertions in line 1) and issue  #18 (correcting the UPPERCASE words in lines 1 and 3) for the file data/a1839745.txt
I have also updated the relevant change log in docs/a1839745.txt
Thanks for your work on maintaining this repository, and please advice me if there are any further changes relating to these files that would be helpful.
Thank you,
Daniel
> Fix for 'XXXXXXX' and UPPERCASE bugs in file data/a1839745.txt

- data/a1851176.txt
- docs/a1851176.txt
Hello,
I've made changes to data/a1851176.txt to remove the unexpected XXXXXX and change the uppercase to lowercase. This fixes issues #20 and #22. I've also logged my changes on the changelog docs/a1851176.txt
Thanks for your project! Hopefully these changes will help.
> Fix issues #20 and #22

- data/a1875420.txt
- docs/a1875420.txt
Hi, 
I've made a couple of fixes in the data/a1875420.txt file, including:
- removed the 'XXXXXXX' placeholder as mentioned in issue #25 
- also converted the UPPERCASE words into lowercase as per issue #28 
Everything's documented in the changelog in docs/a1875420.txt. 
Thanks again for maintaining this project. Let me know if there are any other adjustments needed :D
> fixed issues #25 and #28

- data/a1871922.txt
- docs/a1871922.txt
Hi !
This pull request addresses two issues in the data/a1871922.txt file:
1. The insertion of "XXXXXX" in line 3 has been removed to resolved the bug in issue #26 
2. The UPPERCASE words in line 3 has been corrected to lowercase in issue #27 
Additionally, the changelog in docs/a1871922.txt has been updated to reflect both of these fixes.
Thank you once again for maintaining this project. :)
> Fix issue #26 and #27: resolving XXXXXX and UPPERCASE bug

- data/a1886661.txt
- docs/a1886661.txt
This pull request fixes the following issues:    
1. High severity issue (XXXXXXX) - (https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/2)
- Removed incorrect text from data/a1886661.txt.
2. Low severity issue (UPPERCASE) - (https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/3)
- Fixed UPPERCASE issue in data/a1886661.txt.
> Resolved High Severity (XXXXXXX) and Low Severity (UPPERCASE) Issues in data/a1886661.txt

- data/a1850508.txt
Hi, 
As mentioned in issue #6 and in issue #7 I'm submitting a pull request where I have removed the XXXXX and UPPERCASE bugs.
Any issues please let me know.
> data/a1850508 fix of XXXXX and UPPERCASE Bug

- data/a1851815.txt
- docs/a1851815.txt
Hi there,
This pull request fixes the following issues in the file data/a1851815.txt:
#38 
- Change made: removed 3 instances of 'XXXXXXX' terms 
#39 
- Change made: converted 3 instances of UPPERCASE words to have lowercase letters
Thank you in advance for your review.
Maddie :)
> Fix for #38 and #39: remove 'XXXXXXX' and change UPPERCASE words to lowercase

- data/a1851451.txt
Hi there!
Thank you again for the project! I have learnt a lot.
I pulled the issue for the "XXXXXXX" insertion and the UPPERCASE substitutions in file a1851451.txt.
Thank you again!
> Fixed issue for #40 (XXXXXXX insertion) & #41 (UPPERCASE substitutions) in filedoc/a1851451.txt

- data/a1645191.txt
- docs/a1645191.txt
Hi Dave
This pull request is to resolve bugs in data/a1645191.txt
#70 
In line 3 there were multiple insertions of 'XXXXXXX ' which have now been removed
#71 
In line 3 there were multiple cases of UPPERCASE words which have now been changed to lowercase 
The change log has been updated to include these changes 
Thank you for reviewing these bug fixes 
Deannon
> Resolve issues #70 and #71 

- data/a1954027.txt
- docs/a1954027.txt
Hello there!
This pull request fixes two issues with the data/a1954027.txt file:
#44
Issue 1: High severity bug (XXXXXXX) – The XXXXXXX placeholders were removed from the file, ensuring proper spacing between words.
#45 
Issue 2: Low severity bug (UPPERCASE) – Certain words that were incorrectly capitalized have been converted to lowercase.
Both fixes were applied to the main branch, and the changelog was updated accordingly. Thanks for reviewing these changes!
Sinthia
> Fix issues #44 and #45 by changing the XXXXXXX and UPPERCASE bugs.

- data/a1797428.txt
- docs/a1797428.txt
Hello!
Hope you're doing well! This pull request is in regards to file data/a1797428.txt from the repository. I have tried to resolve a couple of issues that were raised, and the changes are outlined below:
Issue #48 described the inclusion of 'XXXXXXX' three times within Line 1. These have now been removed from the file in both the main and stable branches. 
Issue #49 related to three words within Line 1 that were written in uppercase. These were replaced to lower case in the main branch.
The changelog file has been updated as well, detailing the changes. The final, updated version of the file can be viewed under the commit ae95c1f. 
Hopefully that makes sense! Please let me know if there are any issues. 
Thanks,
Ishjyot Dhindsa
> Issues #48 and #49 for file data/a1797428.txt fixed

- data/a1909154.txt
- docs/a1909154.txt
Hello there!
This pull request addresses two issues in the data/a1909154.txt file:
[#56](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/56)
Issue 1: High severity bug (XXXXXXX) – Removed the XXXXXXX placeholders, ensuring that words have proper spacing between them.
[#57](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/57)
Issue 2: Low severity bug (UPPERCASE) – Corrected incorrectly capitalized words by converting them to lowercase where necessary.
Both fixes were implemented in the main branch, and the changelog was updated to reflect these modifications. Thank you for reviewing these changes!
Best,
Dini
> Issues #56 and #57 for file data/a1909154.txt fixed

- data/a1947736.txt
- docs/a1947736.txt
Hello!
Hope you're doing well! This pull request is in regards to file data/a1947736.txt from the repository. I have tried to resolve a couple of issues that were raised, and the changes are outlined below:
Issue https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/55 described the inclusion of 'XXXXXXX' three times within Line 1 and Line 11. These have now been removed from the file in both the main and stable branches.
Issue https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/58 related to three words within Line 11 that were written in uppercase. These were replaced to lower case in the main branch.
The change log file has been updated as well, detailing the changes. The final, updated version of the file can be viewed under the commit …
> Fix issues #55 and #58 by changing the XXXXXXX and UPPERCASE bugs. 

- data/a1947841.txt
- docs/a1947841.txt
Hello,
I hope you are doing well. This pull request focuses on fixing two bugs of the data/a1947841.txt file. Here's how I did it:
[#65 ](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/65):
It's a high severity bug about unexpected 'XXXXXXX' insertion. I have removed them in both main and stable branches.
[#66 ](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/66):
This is a low severity bug about abrupt UPPERCASE words. I have turn them into lowercase words in the main branch. 
My two commits on the main branch have been affiliated. Hope this can be helpful and it's an honour if you adopt my repo. Please let me know once there's further issue.
Best regards,
Xianzhe Hu
> Resolve issues #65 and #66 about 'XXXXXXX' insertion and UPPERCASE words

- data/a1932615.txt
- docs/a1932615.txt
Hey there!
I have fixed issue #63 and issue #64 
The following changes were made-
For the insertion of XXXXX (issue #63) in lines 1 and 5, I simply deleted them. 
For the presence of UPPERCASE letter (issue #64) in lines 1 (HIT, LIGHT) and line 5(POWER), I switched those words back to lowercase letters. 
Hoping this pull request (for the main branch) gives you one less thing to worry about! Looking forward for your review and approval. Thanks again for your time in this project!
With Regards,
Siddhant
> Fixed issue #63 and issue #64 regarding data/a1932615.txt 

- data/a1904509.txt
- docs/a1904509.txt
This pull request is to fix previously mentioned issues,
issue #77 : 'XXXXXXX' removed from line 1
issue #78 : uppercase words changed to lowercase words in line 1
Thank you for maintaining this repo
> Fixing issue #77 and #78 in data/a1904509.txt

- data/a1901379.txt
- docs/a1901379.txt
Hi there,
This is a pull request to fix the previously mentioned issues as shown below,
issue #79 : High severity issue: data/a1901379.txt contains ‘XXXXXXX’ 
issue #80 : Low severity issue: data/a1901379.txt contains UPPERCASE letters
Thank you for maintaining this repo.
Sincerely,
Kuhu Kinnori
> Fixing issues #79 and #80 in data/a1901379.txt

- data/a1906661.txt
- docs/a1906661.txt
Issues with high severity #59 and low severity #61 are fixed. 
All the 'XXXXXXX' are removed and UPPERCASE letters are replaced with lowercase letters in the file a1906661.txt
Regards,
Sadiq Ali
> Fixes issues with high severity #59 and low severity #61 

- data/a1903005.txt
- docs/a1903005.txt
Hi there, 
This pull request addresses the following two issues in the file data/a1903005.txt: 
#47: Strings of 'XXXXXXX' in lines 3, 5 and 11 were removed. 
#54: UPPERCASE words in lines 11 and 15 were replaced to lowercase. 
Thank you once again for all your hard work!
Brinda
> Fix issue #47 and #54: removal of 'XXXXXXX' and replacement of UPPERCASE words to lowercase

- data/a1843355.txt
- docs/a1843355.txt
Hi,
I am submitting these fixes for the insertion and substitution bugs I raised in #91 and #92; all instances of 'XXXXXXX' insertion were removed, and uppercase strings were changed to lowercase. 
I've also updated the changelog in docs/a1843355.txt to reflect these changes.
It would be great if you could review these fixes and let me know if there is anything I can improve.
Thanks again,
Sinali
> Fixes for #91 'XXXXXXX' insertion and #92 UPPERCASE substitution in file data/a1843355.txt

- data/a1893982.txt
Hello, I hope this message finds you well. Thank you for maintaining this valuable project. I have raised two issues #67 and #68 . As I have promised I have fixed them and am raising this pull request to merge them. 
For issue #67, commit 1b519af and 6e31312 fix the issue in both branches. 
For issue #68, commit ced33d0 fixes the issue for both branches.
I assure that by accepting this pull request does not introduce any new bugs and it benefits the repository  by having removed unwanted letters and having properly formatted text.
Please review the changes at your convenience. I am open to any further adjustments. Thank you for considering this pull request.
Thanks & Regards,
Mansi Rawal
> Resolving issue #67 and #68

- data/a1935423.txt
- docs/a1935423.txt
Hi,
This pull request is regarding the two bugs that I had encountered in file data/a1935423.txt
#21 - The bug where "XXXXXXX" was found in the text has been rectified with the bug being removed and additional spaces being removed.
#23  - The bug where random words in the text were capitalised has been rectified with the altered words being converted to lowercase.
Thank you once again for maintaining this project, it has been really helpful. 
Best,
Ishan
> Fixed issue regarding "XXXXXXX" bug (Issue #21) and random capitalisation (Issue #23)

- data/a1910059.txt
- docs/a1910059.txt
in data/a1910059,
fixed issue "XXXXXXX" in issue number #101 
fixed issue "upper case letter" in issue number #102
> Fixed High and Low severity issue #101 and #102

- data/a1899345.txt
- docs/a1899345.txt
Fixed issue #104 and #105 by removing "XXXXXXX" and replacing uppercase letters with lowercase letters respectively.
Thank you,
Arun Kiran
> Fixed high and low severity issue #104 and #105

- data/a1904204.txt
Hi, 
Thank you for maintaining this repository. i raised issues#137 and #138. I fixed them and raise the pull request for merging it.
commit 176493af9881d119ada3a2bb9cb9bf82475b33cc  and a20d85e1935cc1506df77252824fa9a9cd1bb4d0 for #137 
commit b00e03b57adef5f0faef8f314dcd43a80f55dfda for#138 both are fixed.
I assure no new bugs introduced when the pull request is done.
Thank you 
Greeshma
> Pull request for high and low severity request

- data/a1897552.txt
- docs/a1897552.txt
Hi there! I hope you are well.
This is a pull request addressing the two issues found in file a1897552.txt.
I have fixed the high severity issue #85 by removing the three insertions of 'XXXXXXX'. I have also fixed the low severity issue #86 by changing the three instances of uppercase words to their intended lowercase.
I hope you'll find these changes acceptable. Please let me know if you have any questions about the edits.
Thanks again for your project and your time. 
Kind regards
Komborero Bingudza 
a1897552
> Resolution for high severity issue #85 and for low severity issue #86 in data/a1897552.txt

- CHANGELOG.md
- a1894991.txt
-Fixed the high severity issue in line 1 by removing the placeholder 'xxxxxxx' in 'a1894991.txt'
-Fixed the low-severity issue by changing the UPPERCASE words into lowercase in 'a1894991.txt'.
I also updated the 'CHANGELOG.md' to reflect these changes.
Link of Issues:
-High severity issues: https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/e4acdbec7024f66a4469207717bbbb55dd746531
-Low severity issues:
https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/commit/9a768e0607b097b77e10856cb0f1e0600a2f97fb
> Fixed high severity (xxxxxxx) and low severity UPPERCASE issues in a1894991.txt

- data/a1862759.txt
- docs/a1862759.txt
Commits were made to address two separate bugs. Firstly, 'XXXXXXX' bug in line 3 was fixed. Secondly, uppercase bug in lines 3 and 9 were fixed.
> Fixed 'XXXXXXX' bug (high severity) and uppercase bug (low severity) in file a1862759.txt

- data/a1940870.txt
- docs/a1940870.txt
Hi, Thank you for your constant efforts in maintaining this project.
I fixed the issue #116 regarding high severity bug of insertion of XXXXXXX in file data/a1940870.txt by removing the 3 'XXXXXXX' insertions in line 1. 
I also managed to fix the issue #117 regarding low severity bug of UPPERCASE by changing the uppercase words - NUMBER, PART and PLACE back to lowercase - number, part, place
I would be grateful if you could kindly accept this pull request. Thank you for your time and consideration. 
Kind regards, 
Afreen
> Fixed issues #116  and #117 of file data/a1940870.txt 

- data/a1873151.txt
- docs/a1873151.txt
This pull request addresses the following issues:
- Fixed high severity issue "XXXXXXX" in `data/a1873151.txt`. See [issue #115](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/115).
- Fixed low severity issue "UPPERCASE" in `data/a1873151.txt`. See [issue #118](https://github.com/davmlaw/2024_assignment_5_adelaide_uni_bioinfo/issues/118).
- Removed the `XXXXXXX` in the `data/a1873151.txt` file and ensured there is only one space between the words.
- Corrected UPPERCASE issue by changing wrongly capitalized words to lowercase in `data/a1873151.txt`.
> Fix issues #115 and #118: High and low severity bug fixes in data/a1873151.txt

- data/a1773594.txt
- docs/a1773594.txt
Hello there, 
Hope you're well! I've made this pull request to addresses the following:
- Fixed high severity issue (XXXXXXX) by removing it from the data/a1773594.txt See issue #72
- Fixed low severity issue (UPPERCASE) by removing it from the data/ a1773594.txt See issue #73
Both fixes have been documented in the changelog, under the doc/a1773594.txt 
**Brief description:**
- For issue 72, the inclusion of an unexpected insertion of ‘XXXXXXX’ in lines 1 and 9 has been removed to ensure correct spacing and structure. 
- For issue 73, unexpected capitalization of certain words in line 1 has been edited to match rest of file format. 
Let me know if this helps! 
Kindest Regards,
Alexa
> Fixed high and low severity issues #72 & #73 in data/a1773594.txt 

- data/a1865749.txt
- docs/a1865749.txt
Hi,
Hope you're doing well! This pull request is in regards to file data/a1865749.txt.
Issue #51 is 3 words in line 3 and line 5 are written in uppercase. These were replaced to lower case in the main branch.
Issue #52 described the inclusion of 'XXXXXXX' three times in line 3. These have now been removed from the file in both the main and stable branches.
The changelog file has been updated detailling the changes as well.
Thank you for maintaining the project!
Thu Trang
> Fix #51 and #52 issue in data/a1865749.txt

- data/a1864525.txt
- docs/a1864525.txt
Hi there! 
I took it upon myself to fix two of the issues listed in your repository. These include:
- High Severity Bug in which there were 3 occurrences of "XXXXXXX" appearing randomly in the text.
- Low Severity Bug in which 3 words were written in all uppercase.
- Changes were listed in the Changelog document assigned to the a1864525 data file.
Kind Regards,
Jasper Croot
> High and Low Severity Bug Fixes in data/a1864525.txt

- data/a1869981.txt
Hello there,
I have fixed some high severity and low severity issues on file a1869981.txt. The resolved issues are as below,
- Unnecessary insertion of XXXXXXX was corrected.
- Unexpected changing some lowercase words to UPPERCASE was changed to lowercase letters.
Thank you,
Dilmi Nimnika
> High severity and low severity bugs fixed on a1869981.txt data file

- data/a1868878.txt
- docs/a1868878.txt
Hi there!
This pull request addresses two issues raised:
#111 - High Severity Bug: Insertion of "XXXXXXX" in a1868878.txt (identified in Line 1 and Line 3). 
#112 - Low Severity Bug: UPPERCASE Substitution Issue in a1868878.txt (identified in Line 1).
These changes have been made and updated in the changelog located in docs/a1868878.txt.
Thankyou for your continued work to maintain the functionality of this repository! 
Kind regards,
Jasmine
> Resolution for "XXXXXXX" Insertion and UPPERCASE Substitution Bug Issues a1868878.txt

- data/a1872208.txt
- docs/a1872208.txt
Hello!
This is a pull request aimed at fixing two previously raised issues with the file data/a1872208.txt
f3c07a487975b0f56da99eaa2e35fa4d20f82789: Fixed High Severity Bug "XXXXXXX" insertion in line 1
95159c1a0b19c484783814ef59642214b4a23d70: Fixed Low Severity Bug "UPPERCASE" substitution in lines 1 & 3
The changes have been made and records kept in the changelog found in docs/a1872208.txt
Thank you again for your continued support of this valued repository, hope this fix helps in future!
All the Best,
Jean-Philippe
> Resolution for high severity "XXXXXXX" insertion bug and low severity UPPERCASE substitution bug in file data/a1872208.txt  

- data/a1876866.txt
Dear Dave, 
Thank you for your contribution to the project. This pull request addresses high-severity bugs (issue#140) and low-severity bugs(issue#141) in data/a1876866.txt. A total of two commits were made which include deleting XXXXX insertions and replacing upper letters by lower case letters. Detailed chagelog were written in the doc/a1876866.txt.
> Pull request of fixing high-severity and low severity bugs in data/a1876866.txt
